-- ============================================================
-- ForumWebsite – generated SQL schema (SQL Server)
-- Generated by: dotnet ef migrations script
-- Run after: dotnet ef migrations add InitialCreate
--            dotnet ef database update
-- ============================================================

-- ── Users ─────────────────────────────────────────────────────────────────────
CREATE TABLE [Users] (
    [Id]           INT            NOT NULL IDENTITY,
    [Username]     NVARCHAR(50)   NOT NULL,
    [Email]        NVARCHAR(100)  NOT NULL,
    [PasswordHash] NVARCHAR(MAX)  NOT NULL,
    [Role]         NVARCHAR(20)   NOT NULL DEFAULT N'User',
    [CreatedAt]    DATETIME2      NOT NULL DEFAULT (GETUTCDATE()),
    [UpdatedAt]    DATETIME2      NULL,
    [IsActive]     BIT            NOT NULL DEFAULT CAST(1 AS BIT),
    CONSTRAINT [PK_Users] PRIMARY KEY ([Id])
);

CREATE UNIQUE INDEX [UX_Users_Username] ON [Users] ([Username]);
CREATE UNIQUE INDEX [UX_Users_Email]    ON [Users] ([Email]);

-- ── Posts ─────────────────────────────────────────────────────────────────────
CREATE TABLE [Posts] (
    [Id]        INT            NOT NULL IDENTITY,
    [Title]     NVARCHAR(300)  NOT NULL,
    [Content]   NVARCHAR(MAX)  NOT NULL,
    [UserId]    INT            NOT NULL,
    [ViewCount] INT            NOT NULL DEFAULT 0,
    [CreatedAt] DATETIME2      NOT NULL DEFAULT (GETUTCDATE()),
    [UpdatedAt] DATETIME2      NULL,
    [IsDeleted] BIT            NOT NULL DEFAULT CAST(0 AS BIT),
    CONSTRAINT [PK_Posts]          PRIMARY KEY ([Id]),
    CONSTRAINT [FK_Posts_Users_UserId]
        FOREIGN KEY ([UserId]) REFERENCES [Users] ([Id]) ON DELETE NO ACTION
);

CREATE INDEX [IX_Posts_UserId]    ON [Posts] ([UserId]);
CREATE INDEX [IX_Posts_CreatedAt] ON [Posts] ([CreatedAt]);
CREATE INDEX [IX_Posts_IsDeleted] ON [Posts] ([IsDeleted]);

-- ── Comments ──────────────────────────────────────────────────────────────────
CREATE TABLE [Comments] (
    [Id]        INT            NOT NULL IDENTITY,
    [Content]   NVARCHAR(5000) NOT NULL,
    [PostId]    INT            NOT NULL,
    [UserId]    INT            NOT NULL,
    [CreatedAt] DATETIME2      NOT NULL DEFAULT (GETUTCDATE()),
    [UpdatedAt] DATETIME2      NULL,
    [IsDeleted] BIT            NOT NULL DEFAULT CAST(0 AS BIT),
    CONSTRAINT [PK_Comments]              PRIMARY KEY ([Id]),
    CONSTRAINT [FK_Comments_Posts_PostId]
        FOREIGN KEY ([PostId]) REFERENCES [Posts] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_Comments_Users_UserId]
        FOREIGN KEY ([UserId]) REFERENCES [Users] ([Id]) ON DELETE NO ACTION
);

CREATE INDEX [IX_Comments_PostId] ON [Comments] ([PostId]);
CREATE INDEX [IX_Comments_UserId] ON [Comments] ([UserId]);
